/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineshoeshop;

import javax.swing.JOptionPane;

/**
 *
 * @author Abdul Hakim D
 */
public class Home2 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        deskProduk = new javax.swing.JPanel();
        SlideBar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        bSlideBar = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSlideBar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produkPanel = new javax.swing.JPanel();
        prod1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        prod2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        prod3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        prod4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        prod5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        prod6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        deskProduk.setBackground(new java.awt.Color(102, 255, 51));
        getContentPane().add(deskProduk);
        deskProduk.setBounds(0, 0, 0, 600);

        SlideBar.setBackground(new java.awt.Color(255, 255, 153));
        SlideBar.setRequestFocusEnabled(false);
        SlideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton1.setText("PROFILE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(300, 50));
        SlideBar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 148, -1, -1));

        bSlideBar.setPreferredSize(new java.awt.Dimension(30, 10));
        bSlideBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSlideBarActionPerformed(evt);
            }
        });
        SlideBar.add(bSlideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 5, -1, -1));

        getContentPane().add(SlideBar);
        SlideBar.setBounds(0, 0, 0, 600);

        namePanel.setBackground(new java.awt.Color(255, 204, 255));
        namePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/solesphere_logo3-removebg-preview.png"))); // NOI18N
        namePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        bSlideBar1.setPreferredSize(new java.awt.Dimension(30, 10));
        bSlideBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSlideBar1ActionPerformed(evt);
            }
        });
        namePanel.add(bSlideBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas_ppbo/solesphere_logo3-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel27);

        namePanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 100));

        getContentPane().add(namePanel);
        namePanel.setBounds(0, 0, 360, 120);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        produkPanel.setPreferredSize(new java.awt.Dimension(360, 800));
        produkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prod1.setBackground(new java.awt.Color(255, 204, 255));
        prod1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        prod1.setPreferredSize(new java.awt.Dimension(160, 200));
        prod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prod1MouseClicked(evt);
            }
        });
        prod1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("New Balance");
        jLabel3.setPreferredSize(new java.awt.Dimension(160, 35));
        prod1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rp. 2.000.000");
        jLabel4.setPreferredSize(new java.awt.Dimension(160, 45));
        prod1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FRESH FOAM X 1080V13");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setPreferredSize(new java.awt.Dimension(160, 35));
        prod1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nb_1080v13__1_-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel26);

        prod1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        produkPanel.add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        prod2.setBackground(new java.awt.Color(255, 204, 255));
        prod2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        prod2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prod2MouseClicked(evt);
            }
        });
        prod2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("New Balance");
        jLabel7.setPreferredSize(new java.awt.Dimension(160, 35));
        prod2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rp. 2.000.000");
        jLabel8.setPreferredSize(new java.awt.Dimension(160, 45));
        prod2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MADE IN USA 990V6");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 35));
        prod2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/990v6__1_-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel6);

        prod2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        produkPanel.add(prod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        prod3.setBackground(new java.awt.Color(255, 204, 255));
        prod3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        prod3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("New Balance");
        jLabel11.setPreferredSize(new java.awt.Dimension(160, 35));
        prod3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Rp. 2.000.000");
        jLabel12.setPreferredSize(new java.awt.Dimension(160, 45));
        prod3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("WOMEN'S 550");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setPreferredSize(new java.awt.Dimension(160, 35));
        prod3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Womens_550__1_-removebg-preview.png"))); // NOI18N
        jPanel4.add(jLabel10);

        prod3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        produkPanel.add(prod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        prod4.setBackground(new java.awt.Color(255, 204, 255));
        prod4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        prod4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("New Balance");
        jLabel15.setPreferredSize(new java.awt.Dimension(160, 35));
        prod4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Rp. 2.000.000");
        jLabel16.setPreferredSize(new java.awt.Dimension(160, 45));
        prod4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("1540V3");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setPreferredSize(new java.awt.Dimension(160, 35));
        prod4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NB_1540V3__1_-removebg-preview.png"))); // NOI18N
        jPanel5.add(jLabel28);

        prod4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        produkPanel.add(prod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        prod5.setBackground(new java.awt.Color(255, 204, 255));
        prod5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        prod5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("New Balance");
        jLabel19.setPreferredSize(new java.awt.Dimension(160, 35));
        prod5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Rp. 2.000.000");
        jLabel20.setPreferredSize(new java.awt.Dimension(160, 45));
        prod5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("9060");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel21.setPreferredSize(new java.awt.Dimension(160, 35));
        prod5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 20));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NB_9060__1_-removebg-preview.png"))); // NOI18N
        jPanel6.add(jLabel29);

        prod5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        produkPanel.add(prod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        prod6.setBackground(new java.awt.Color(255, 204, 255));
        prod6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        prod6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("New Balance");
        jLabel23.setPreferredSize(new java.awt.Dimension(160, 35));
        prod6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Rp. 2.000.000");
        jLabel24.setPreferredSize(new java.awt.Dimension(160, 45));
        prod6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("928V3");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel25.setPreferredSize(new java.awt.Dimension(160, 35));
        prod6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/928V3__1_-removebg-preview.png"))); // NOI18N
        jPanel7.add(jLabel30);

        prod6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        produkPanel.add(prod6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jScrollPane2.setViewportView(produkPanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 120, 360, 480);

        setSize(new java.awt.Dimension(362, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSlideBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSlideBarActionPerformed
        // TODO add your handling code here:
        try {
            for(int i=300; i>=0; i--){
                SlideBar.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        bSlideBar1.show();
    }//GEN-LAST:event_bSlideBarActionPerformed

    private void bSlideBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSlideBar1ActionPerformed
        // TODO add your handling code here:
        try {
            for(int i=0; i<=300; i++){
                SlideBar.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        bSlideBar1.hide();
    }//GEN-LAST:event_bSlideBar1ActionPerformed

    private void prod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prod1MouseClicked
        // TODO add your handling code here:
        try {
            for(int i=0; i>=360; i++){
                deskProduk.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_prod1MouseClicked

    private void prod2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prod2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_prod2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SlideBar;
    private javax.swing.JButton bSlideBar;
    private javax.swing.JButton bSlideBar1;
    private javax.swing.JPanel deskProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel namePanel;
    private javax.swing.JPanel prod1;
    private javax.swing.JPanel prod2;
    private javax.swing.JPanel prod3;
    private javax.swing.JPanel prod4;
    private javax.swing.JPanel prod5;
    private javax.swing.JPanel prod6;
    private javax.swing.JPanel produkPanel;
    // End of variables declaration//GEN-END:variables
}
