/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineshoeshop;
import com.mysql.cj.jdbc.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdul Hakim D
 */
public class myCart extends javax.swing.JFrame {
    public String brand;
    public String nm_sepatu;
    public int harga;
    public String ukuran;
    /**
     * Creates new form myCart
     */
    public myCart() {
        initComponents();
        isiCart();
    }
    
    private void isiCart() {
        try {
            products2 pd = new products2();
            pd.koneksiDatabase();
            Login lg = new Login();
            pullFromDB(pd.getConnection(), lg.usernameLogin);
            
            lbrand.setText(brand);
            lnama.setText(nm_sepatu);
            lukuran.setText(ukuran);
            lHarga1.setText("Rp."+Integer.toString(harga));
            lTotal1.setText("Rp."+Integer.toString(harga));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void pullFromDB(Connection con, String username) {
        try {
            String userN = username.concat("_cart");
            String query = "SELECT * FROM " + userN;
            
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            
            if (resultSet.next()) {
                brand = resultSet.getString("brand");
                nm_sepatu = resultSet.getString("nm_sepatu");
                harga = resultSet.getInt("harga");
                ukuran = resultSet.getString("ukuran");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SlideBar = new javax.swing.JPanel();
        bSlideBar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sbName = new javax.swing.JLabel();
        sbUsername = new javax.swing.JLabel();
        sbProfile = new javax.swing.JLabel();
        sbMyCart = new javax.swing.JLabel();
        sbMyHistory = new javax.swing.JLabel();
        sbHome = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSlideBar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        produkPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lnama = new javax.swing.JLabel();
        lbrand = new javax.swing.JLabel();
        lukuran = new javax.swing.JLabel();
        lHarga1 = new javax.swing.JLabel();
        lGambar1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lTotal = new javax.swing.JLabel();
        lTotal1 = new javax.swing.JLabel();
        bCheckout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 600));
        setPreferredSize(new java.awt.Dimension(360, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        SlideBar.setBackground(new java.awt.Color(255, 255, 122));
        SlideBar.setRequestFocusEnabled(false);
        SlideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSlideBar.setPreferredSize(new java.awt.Dimension(30, 10));
        bSlideBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSlideBarActionPerformed(evt);
            }
        });
        SlideBar.add(bSlideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 5, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.jpeg"))); // NOI18N
        SlideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sbName.setText("Nama");
        sbName.setPreferredSize(new java.awt.Dimension(180, 20));
        SlideBar.add(sbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 65, -1, -1));

        sbUsername.setText("Username");
        sbUsername.setPreferredSize(new java.awt.Dimension(180, 20));
        SlideBar.add(sbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 85, -1, -1));

        sbProfile.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbProfile.setForeground(new java.awt.Color(255, 255, 255));
        sbProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account-profile-user-icon--icon-search-engine-10.png"))); // NOI18N
        sbProfile.setText("PROFILE");
        sbProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbProfile.setIconTextGap(20);
        sbProfile.setPreferredSize(new java.awt.Dimension(300, 50));
        sbProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbProfileMouseClicked(evt);
            }
        });
        SlideBar.add(sbProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        sbMyCart.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbMyCart.setForeground(new java.awt.Color(255, 255, 255));
        sbMyCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ikon keranjang as Smart Object-1.png"))); // NOI18N
        sbMyCart.setText("MY CART");
        sbMyCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbMyCart.setIconTextGap(20);
        sbMyCart.setPreferredSize(new java.awt.Dimension(300, 50));
        sbMyCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbMyCartMouseClicked(evt);
            }
        });
        SlideBar.add(sbMyCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        sbMyHistory.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbMyHistory.setForeground(new java.awt.Color(255, 255, 255));
        sbMyHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/computer-icons-user-story-computer-software-history as Smart Object-1.png"))); // NOI18N
        sbMyHistory.setText("MY HISTORY");
        sbMyHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbMyHistory.setIconTextGap(20);
        sbMyHistory.setPreferredSize(new java.awt.Dimension(300, 50));
        sbMyHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbMyHistoryMouseClicked(evt);
            }
        });
        SlideBar.add(sbMyHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        sbHome.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbHome.setForeground(new java.awt.Color(255, 255, 255));
        sbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home Icon as Smart Object-1.png"))); // NOI18N
        sbHome.setText("HOME");
        sbHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbHome.setIconTextGap(20);
        sbHome.setPreferredSize(new java.awt.Dimension(300, 50));
        sbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbHomeMouseClicked(evt);
            }
        });
        SlideBar.add(sbHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        getContentPane().add(SlideBar);
        SlideBar.setBounds(0, 0, 0, 600);

        namePanel.setBackground(new java.awt.Color(255, 204, 255));
        namePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/solesphere_logo3-removebg-preview.png"))); // NOI18N
        namePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        bSlideBar1.setPreferredSize(new java.awt.Dimension(30, 10));
        bSlideBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSlideBar1ActionPerformed(evt);
            }
        });
        namePanel.add(bSlideBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        getContentPane().add(namePanel);
        namePanel.setBounds(0, 0, 360, 120);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(360, 400));

        produkPanel.setPreferredSize(new java.awt.Dimension(360, 800));
        produkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnama.setText("Ukuran");
        lnama.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        lbrand.setText("Brand");
        lbrand.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        lukuran.setText("Warna");
        lukuran.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lHarga1.setText("Harga");
        lHarga1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, -1));

        lGambar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineshoeshop/nb 1080v13 (3) cart.jpg"))); // NOI18N
        jPanel1.add(lGambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        produkPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jScrollPane2.setViewportView(produkPanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 120, 360, 400);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTotal.setText("TOTAL");
        lTotal.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel2.add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lTotal1.setText("Rp. 2.000.000");
        lTotal1.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel2.add(lTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        bCheckout.setBackground(new java.awt.Color(153, 255, 153));
        bCheckout.setText("Checkout");
        bCheckout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCheckout.setPreferredSize(new java.awt.Dimension(100, 40));
        bCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckoutActionPerformed(evt);
            }
        });
        jPanel2.add(bCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 520, 360, 80);

        setSize(new java.awt.Dimension(376, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSlideBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSlideBarActionPerformed
        // TODO add your handling code here:
        try {
            for(int i=300; i>=0; i--){
                SlideBar.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        bSlideBar1.show();
    }//GEN-LAST:event_bSlideBarActionPerformed

    private void bSlideBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSlideBar1ActionPerformed
        // TODO add your handling code here:
        try {
            for(int i=0; i<=300; i++){
                SlideBar.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        bSlideBar1.hide();
    }//GEN-LAST:event_bSlideBar1ActionPerformed

    private void sbProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbProfileMouseClicked
        // TODO add your handling code here:
        Profile pf = new Profile();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
        pf.setDefaultCloseOperation(Profile.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbProfileMouseClicked

    private void sbMyCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMyCartMouseClicked
        // TODO add your handling code here:
        myCart mc = new myCart();
        mc.setVisible(true);
        mc.setLocationRelativeTo(null);
        mc.setDefaultCloseOperation(myCart.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbMyCartMouseClicked

    private void sbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbHomeMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Home.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbHomeMouseClicked

    private void sbMyHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMyHistoryMouseClicked
        // TODO add your handling code here:
        myHistory mh = new myHistory();
        mh.setVisible(true);
        mh.setLocationRelativeTo(null);
        mh.setDefaultCloseOperation(myHistory.DISPOSE_ON_CLOSE);
        dispose();
        
    }//GEN-LAST:event_sbMyHistoryMouseClicked
    private void saveToDatabase(Connection conn, String username) {
        try {
            // Query untuk menyimpan data ke tabel akun
            String userN = username.concat("_pembayaran");
            String query = "INSERT INTO " + userN + " (brand, nm_sepatu, harga, ukuran) VALUES (?, ?, ?, ?)";

            // Persiapan statement
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            preparedStatement.setString(1, this.lbrand.getText());
            preparedStatement.setString(2, this.lnama.getText());
            preparedStatement.setInt(3, this.harga);
            preparedStatement.setString(4, this.lukuran.getText());
            // Eksekusi query
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Data inserted successfully!");
            } else {
                System.out.println("Failed to insert data!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void bCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckoutActionPerformed
        // TODO add your handling code here:
        try {
            products2 pd = new products2();
            pd.koneksiDatabase();
            Login lg = new Login();
            saveToDatabase(pd.getConnection(), lg.usernameLogin);
            Pembayaran pb = new Pembayaran();
            pb.setVisible(true);
            pb.setLocationRelativeTo(null);
            pb.setDefaultCloseOperation(Pembayaran.DISPOSE_ON_CLOSE);
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SlideBar;
    private javax.swing.JButton bCheckout;
    private javax.swing.JButton bSlideBar;
    private javax.swing.JButton bSlideBar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lGambar1;
    private javax.swing.JLabel lHarga1;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lTotal1;
    private javax.swing.JLabel lbrand;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel lukuran;
    private javax.swing.JPanel namePanel;
    private javax.swing.JPanel produkPanel;
    private javax.swing.JLabel sbHome;
    private javax.swing.JLabel sbMyCart;
    private javax.swing.JLabel sbMyHistory;
    private javax.swing.JLabel sbName;
    private javax.swing.JLabel sbProfile;
    private javax.swing.JLabel sbUsername;
    // End of variables declaration//GEN-END:variables
}
