/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineshoeshop;
import com.mysql.cj.jdbc.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdul Hakim D
 */
public class myHistory extends javax.swing.JFrame {
    public String brand;
    public String nm_sepatu;
    public String ukuran;
    public int harga;
    /**
     * Creates new form myHistory
     */
    public myHistory() {
        initComponents();
    }
    
    public void isiHistory() {
        products2 pd = new products2();
        pd.koneksiDatabase();
        Login lg = new Login();
        pullFromDB(pd.getConnection(), lg.usernameLogin);
    }
    
    private void pullFromDB(Connection con, String username) {
        try {
            String userN = username.concat("_cart");
            String query = "SELECT * FROM " + userN;
            
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            
            if (resultSet.next()) {
                brand = resultSet.getString("brand");
                nm_sepatu = resultSet.getString("nm_sepatu");
                harga = resultSet.getInt("harga");
                ukuran = resultSet.getString("ukuran");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SlideBar = new javax.swing.JPanel();
        bSlideBar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sbName = new javax.swing.JLabel();
        sbUsername = new javax.swing.JLabel();
        sbProfile = new javax.swing.JLabel();
        sbMyCart = new javax.swing.JLabel();
        sbMyHistory = new javax.swing.JLabel();
        sbHome = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSlideBar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produkPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lUkuran1 = new javax.swing.JLabel();
        lnama1 = new javax.swing.JLabel();
        lWarna1 = new javax.swing.JLabel();
        lHarga1 = new javax.swing.JLabel();
        lGambar1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lTotal = new javax.swing.JLabel();
        lTotal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        SlideBar.setBackground(new java.awt.Color(255, 255, 122));
        SlideBar.setRequestFocusEnabled(false);
        SlideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSlideBar.setPreferredSize(new java.awt.Dimension(30, 10));
        bSlideBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSlideBarActionPerformed(evt);
            }
        });
        SlideBar.add(bSlideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 5, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.jpeg"))); // NOI18N
        SlideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sbName.setText("Nama");
        sbName.setPreferredSize(new java.awt.Dimension(180, 20));
        SlideBar.add(sbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 65, -1, -1));

        sbUsername.setText("Username");
        sbUsername.setPreferredSize(new java.awt.Dimension(180, 20));
        SlideBar.add(sbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 85, -1, -1));

        sbProfile.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbProfile.setForeground(new java.awt.Color(255, 255, 255));
        sbProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account-profile-user-icon--icon-search-engine-10.png"))); // NOI18N
        sbProfile.setText("PROFILE");
        sbProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbProfile.setIconTextGap(20);
        sbProfile.setPreferredSize(new java.awt.Dimension(300, 50));
        sbProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbProfileMouseClicked(evt);
            }
        });
        SlideBar.add(sbProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        sbMyCart.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbMyCart.setForeground(new java.awt.Color(255, 255, 255));
        sbMyCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ikon keranjang as Smart Object-1.png"))); // NOI18N
        sbMyCart.setText("MY CART");
        sbMyCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbMyCart.setIconTextGap(20);
        sbMyCart.setPreferredSize(new java.awt.Dimension(300, 50));
        sbMyCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbMyCartMouseClicked(evt);
            }
        });
        SlideBar.add(sbMyCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        sbMyHistory.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbMyHistory.setForeground(new java.awt.Color(255, 255, 255));
        sbMyHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/computer-icons-user-story-computer-software-history as Smart Object-1.png"))); // NOI18N
        sbMyHistory.setText("MY HISTORY");
        sbMyHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbMyHistory.setIconTextGap(20);
        sbMyHistory.setPreferredSize(new java.awt.Dimension(300, 50));
        sbMyHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbMyHistoryMouseClicked(evt);
            }
        });
        SlideBar.add(sbMyHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        sbHome.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        sbHome.setForeground(new java.awt.Color(255, 255, 255));
        sbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home Icon as Smart Object-1.png"))); // NOI18N
        sbHome.setText("HOME");
        sbHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sbHome.setIconTextGap(20);
        sbHome.setPreferredSize(new java.awt.Dimension(300, 50));
        sbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbHomeMouseClicked(evt);
            }
        });
        SlideBar.add(sbHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        getContentPane().add(SlideBar);
        SlideBar.setBounds(0, 0, 0, 600);

        namePanel.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineshoeshop/solesphere_logo3-removebg-preview.png"))); // NOI18N

        bSlideBar1.setPreferredSize(new java.awt.Dimension(30, 10));
        bSlideBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSlideBar1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel27)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("STATUS PEMESANAN");

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(bSlideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(bSlideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(namePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))))
        );

        getContentPane().add(namePanel);
        namePanel.setBounds(0, 0, 360, 120);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(360, 400));

        produkPanel.setBackground(new java.awt.Color(255, 204, 255));
        produkPanel.setPreferredSize(new java.awt.Dimension(360, 800));
        produkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lUkuran1.setText("Ukuran");
        lUkuran1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lUkuran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, -1, -1));

        lnama1.setText("Nama");
        lnama1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        lWarna1.setText("Warna");
        lWarna1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lWarna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lHarga1.setText("Harga");
        lHarga1.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel1.add(lHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, -1));

        lGambar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineshoeshop/nb 1080v13 (3) cart.jpg"))); // NOI18N
        jPanel1.add(lGambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        produkPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Status Pemesanan : On-going");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        produkPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, -1));

        jScrollPane2.setViewportView(produkPanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 120, 360, 400);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTotal.setText("TOTAL");
        lTotal.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel2.add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lTotal1.setText("Rp. 2.560.000");
        lTotal1.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel2.add(lTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 520, 360, 80);

        setBounds(0, 0, 376, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void bSlideBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSlideBarActionPerformed
        // TODO add your handling code here:
        try {
            for(int i=300; i>=0; i--){
                SlideBar.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        bSlideBar1.show();
    }//GEN-LAST:event_bSlideBarActionPerformed

    private void sbProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbProfileMouseClicked
        // TODO add your handling code here:
        Profile pf = new Profile();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
        pf.setDefaultCloseOperation(Profile.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbProfileMouseClicked

    private void sbMyCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMyCartMouseClicked
        // TODO add your handling code here:
        myCart mc = new myCart();
        mc.setVisible(true);
        mc.setLocationRelativeTo(null);
        mc.setDefaultCloseOperation(myCart.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbMyCartMouseClicked

    private void sbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbHomeMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Home.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbHomeMouseClicked

    private void bSlideBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSlideBar1ActionPerformed
        // TODO add your handling code here:
        try {
            for(int i=0; i<=300; i++){
                SlideBar.setSize(i, 600);
                Thread.sleep(1);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        bSlideBar1.hide();
    }//GEN-LAST:event_bSlideBar1ActionPerformed

    private void sbMyHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbMyHistoryMouseClicked
        // TODO add your handling code here:
        myHistory mh = new myHistory();
        mh.setVisible(true);
        mh.setLocationRelativeTo(null);
        mh.setDefaultCloseOperation(myHistory.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sbMyHistoryMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("Status Pemesanan : Selesai");
        jButton1.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SlideBar;
    private javax.swing.JButton bSlideBar;
    private javax.swing.JButton bSlideBar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lGambar1;
    private javax.swing.JLabel lHarga1;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lTotal1;
    private javax.swing.JLabel lUkuran1;
    private javax.swing.JLabel lWarna1;
    private javax.swing.JLabel lnama1;
    private javax.swing.JPanel namePanel;
    private javax.swing.JPanel produkPanel;
    private javax.swing.JLabel sbHome;
    private javax.swing.JLabel sbMyCart;
    private javax.swing.JLabel sbMyHistory;
    private javax.swing.JLabel sbName;
    private javax.swing.JLabel sbProfile;
    private javax.swing.JLabel sbUsername;
    // End of variables declaration//GEN-END:variables
}
