package onlineshoeshop;
import com.mysql.cj.jdbc.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Pembayaran extends javax.swing.JFrame {
    public String alamat;
    public String brand;
    public String nm_sepatu;
    public String ukuran;
    public int harga;
    /**
     * Creates new form mainMenu
     */
    public Pembayaran() {
        initComponents();
    }
    
    public void isiAlamat() {
        Register reg = new Register();
        reg.koneksiDatabase();
        Login lg = new Login();
        pullFromDB(reg.getConnection(), lg.usernameLogin);
        
        taAlamat.setText(alamat);
        taAlamat.setEditable(false);
    }
    
    private void isiProduk() {
        try {
            products2 pd = new products2();
            pd.koneksiDatabase();
            Login lg = new Login();
            pullFromDB2(pd.getConnection(), lg.usernameLogin);
            
            lbrand.setText(brand);
            lnama.setText(nm_sepatu);
            lukuran.setText(ukuran);
            lharga.setText("Rp."+Integer.toString(harga));
            lTotal.setText("Rp."+Integer.toString(harga));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void pullFromDB2(Connection con, String username) {
        try {
            String userN = username.concat("_cart");
            String query = "SELECT * FROM " + userN;
            
            PreparedStatement preparedStatement = con.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();
            
            if (resultSet.next()) {
                brand = resultSet.getString("brand");
                nm_sepatu = resultSet.getString("nm_sepatu");
                harga = resultSet.getInt("harga");
                ukuran = resultSet.getString("ukuran");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void pullFromDB(Connection con, String username) {
        try {
            String query = "SELECT alamat FROM akun WHERE username = ?";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, username);
            
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                alamat = resultSet.getString("alamat");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbrand = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        lukuran = new javax.swing.JLabel();
        lharga = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(360, 1200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(360, 600));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 45, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineshoeshop/solesphere_logo3-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 6, -1, 101));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alamat Pengiriman");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 5, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineshoeshop/nb 1080v13 (3) cart.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 100));

        lbrand.setText("Nama Sepatu");
        jPanel2.add(lbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 68, -1, -1));

        lnama.setText("Warna Sepatu");
        jPanel2.add(lnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 90, -1, -1));

        lukuran.setText("Ukuran Sepatu");
        jPanel2.add(lukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 112, -1, -1));

        lharga.setText("Total Harga");
        jPanel2.add(lharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 134, -1, -1));

        taAlamat.setColumns(20);
        taAlamat.setLineWrap(true);
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 350, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 113, 360, 174));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("TOTAL :");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 45, 20));

        lTotal.setText("Rp. 2.000.000");
        lTotal.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel6.add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 360, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Pilih Metode Pembayaran");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COD", "Transfer Bank", "SolespherePay" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 6, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 293, 360, 30));

        jButton1.setText("Buat Pesanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, 40));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 360, 600);

        setSize(new java.awt.Dimension(376, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        products2 pd = new products2();
        pd.koneksiDatabase();
        Login lg = new Login();
        truncateTabel(pd.getConnection(), lg.usernameLogin);
        myCart mc = new myCart();
        mc.setVisible(true);
        mc.setLocationRelativeTo(null);
        mc.setDefaultCloseOperation(myCart.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void truncateTabel(Connection conn, String username) {
        try {
        String userN = username.concat("_history");
        String query = "DLETE FROM "+userN+" WHERE harga > 0";
        
        PreparedStatement preparedStatement = conn.prepareStatement(query);
        int rowsAffected = preparedStatement.executeUpdate();
        if (rowsAffected > 0) {
                System.out.println("Data deleted successfully!");
            } else {
                System.out.println("Failed to deleted data!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void saveToDatabase(Connection conn, String username) {
        try {
            // Query untuk menyimpan data ke tabel akun
            String userN = username.concat("_history");
            String query = "INSERT INTO " + userN + " (brand, nm_sepatu, harga, ukuran) VALUES (?, ?, ?, ?)";

            // Persiapan statement
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            preparedStatement.setString(1, this.lbrand.getText());
            preparedStatement.setString(2, this.lnama.getText());
            preparedStatement.setInt(3, this.harga);
            preparedStatement.setString(4, ukuran);
            // Eksekusi query
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Data inserted successfully!");
            } else {
                System.out.println("Failed to insert data!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            products2 pd = new products2();
            pd.koneksiDatabase();
            Login lg = new Login();
            saveToDatabase(pd.getConnection(), lg.usernameLogin);
            Home hm = new Home();
            hm.setVisible(true);
            hm.setLocationRelativeTo(null);
            hm.setDefaultCloseOperation(Home.DISPOSE_ON_CLOSE);
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lbrand;
    private javax.swing.JLabel lharga;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel lukuran;
    private javax.swing.JTextArea taAlamat;
    // End of variables declaration//GEN-END:variables
}
