package onlineshoeshop;

import com.mysql.cj.jdbc.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdul Hakim D
 */
public class Register extends javax.swing.JFrame {
    public Statement St;
    public Connection con;
    public ResultSet Rs;
    public String sql="";
    /**
     * Creates new form Register
     */
    public String nama;
    public String email;
    public String no_hp;
    public String username;
    public String password;
    public String alamat;
    public String tglLahir;
    public String jKel;
    public Register() {
        initComponents();
    }
    
    public void koneksiDatabase(){
        try {
            //menentukan driver database
            Class.forName("com.mysql.cj.jdbc.Driver");
            //untuk mengkoneksikan ke database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tokosepatu", "root", "");
            //pesan koneksi berhasil
            System.out.println("koneksi berhasil!");
        } catch (Exception e) {
            //pesan koneksi gagal
            System.out.println("koneksi gagal!" + e.getMessage());
        }
    }
    
    Connection getConnection() {
        return con; 
    }
    
    public void disconnect() {
        try {
            if (con != null && !con.isClosed()) {
                con.close();
                System.out.println("Connection closed!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bRegister = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtReTypePassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbJKel = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtTglLahir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setMinimumSize(new java.awt.Dimension(360, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 440));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HELLO !");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 360, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Please insert your data :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 87, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 164, 67, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 160, 179, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 380, 99, -1));

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel2.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 179, 69));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Username");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 290, 67, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 290, 179, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 330, 67, -1));

        bRegister.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(bRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 320, 179, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Re-type Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 350, 99, -1));
        jPanel2.add(txtReTypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 179, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Email");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 130, 67, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 126, 179, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("No.Hp");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 198, 67, -1));

        txtNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHpActionPerformed(evt);
            }
        });
        jPanel2.add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 194, 179, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Jenis Kelamin");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 230, 80, -1));

        cbJKel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        cbJKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJKelActionPerformed(evt);
            }
        });
        jPanel2.add(cbJKel, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 230, -1, -1));

        jLabel13.setText("Tanggal Lahir");
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 260, -1, -1));

        txtTglLahir.setPreferredSize(new java.awt.Dimension(230, 20));
        jPanel2.add(txtTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 260, 179, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -2, 360, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed
    
    private void newAkun(Connection conn) {
        try {
            // Query untuk menyimpan data ke tabel akunF
            String tableName = this.username.concat("_cart");
            String query1 = "CREATE TABLE " + tableName + " (brand VARCHAR(25), nm_sepatu VARCHAR(50), ukuran VARCHAR(2), harga INT(8))";
            
            tableName = this.username.concat("_history");
            String query2 = "CREATE TABLE " + tableName + " (brand VARCHAR(25), nm_sepatu VARCHAR(50), ukuran VARCHAR(2), harga INT(8))";
            
            tableName = this.username.concat("_pembayaran");
            String query3 = "CREATE TABLE " + tableName + " (brand VARCHAR(25), nm_sepatu VARCHAR(50), ukuran VARCHAR(2), harga INT(8))";
            // Persiapan statement
            PreparedStatement preparedStatement = conn.prepareStatement(query1);
            PreparedStatement preparedStatement2 = conn.prepareStatement(query2);
            PreparedStatement preparedStatement3 = conn.prepareStatement(query3);

            // Eksekusi query
            int rowsAffected = preparedStatement.executeUpdate();
            int rowsAffected2 = preparedStatement2.executeUpdate();
            int rowsAffected3 = preparedStatement3.executeUpdate();
            System.out.println("oke berhasil");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void saveToDatabase(Connection conn) {
        try {
            // Query untuk menyimpan data ke tabel akun
            String query = "INSERT INTO akun (email, nama, no_hp, username, password, alamat, jKel, tglLahir) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            // Persiapan statement
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            preparedStatement.setString(1, this.email);
            preparedStatement.setString(2, this.nama);
            preparedStatement.setString(3, this.no_hp);
            preparedStatement.setString(4, this.username);
            preparedStatement.setString(5, this.password);
            preparedStatement.setString(6, this.alamat);
            preparedStatement.setString(7, this.jKel);
            preparedStatement.setString(8, this.tglLahir);

            // Eksekusi query
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Data inserted successfully!");
            } else {
                System.out.println("Failed to insert data!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
        boolean terisi = true;
        
        if(txtEmail.getText().isBlank() || txtName.getText().isBlank() || txtNoHp.getText().isBlank() || txtUsername.getText().isBlank() || txtPassword.getText().isBlank() || txtAlamat.getText().isBlank() || txtReTypePassword.getText().isBlank() || txtTglLahir.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Semua Field Harus diisi!");
            terisi = false;
        }
        
        else if(txtReTypePassword.getText().equals(txtPassword.getText()) && terisi){
            email = txtEmail.getText();
            nama = txtName.getText();
            no_hp = txtNoHp.getText();
            jKel = (String) cbJKel.getSelectedItem();
            tglLahir = txtTglLahir.getText();
            username = txtUsername.getText();
            password = txtPassword.getText();
            alamat = txtAlamat.getText();
            
            Login lg = new Login();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE);
            dispose();
            
            koneksiDatabase();
            saveToDatabase(getConnection());
            newAkun(getConnection());
        } else {
            JOptionPane.showMessageDialog(null,"Re-Type Password Tidak Sesuai");
        }
    }//GEN-LAST:event_bRegisterActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void cbJKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJKelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegister;
    private javax.swing.JComboBox<String> cbJKel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReTypePassword;
    private javax.swing.JTextField txtTglLahir;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
